spring:
  application:
    name: catalog-service
  profiles:
    active: staging
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogdb
    driver-class-name: org.postgresql.Driver
    username: cataloguser
    password: catalogpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
message: Dev profile
